image:
  repository: ghcr.io/ucl-arc-tre/egress
  # Overrides the image tag whose default is the chart appVersion
  tag: null

replicaCount: 1

# Pod resources
resources:
  requests:
    cpu: 10m
    memory: 64Mi

terminationGracePeriodSeconds: 30

# The Kubernetes Service that clients can connect to.
service:
  type: ClusterIP
  nodePort: null
  port: 80

dev:
  # Will expect to be able to mount in this repository under /repo
  hot_reload: false
  s3:
    # URL override for S3. Required for rustfs
    url: null
    # Name of the bucket to create on init for dev
    bucket: null

# Should debug logs be enabled
debug: false

# S3 configuration
s3:
  region: null
  access_key_id: null
  secret_access_key: null

# DB configuration
db:
  provider: null
  baseUrl: null
  username: null
  password: null

# Auth configuration
auth:
  basic:
    username: null
    password: null
