image:
  repository: localhost/ucl-arc-tre-egress
  tag: dev

replicaCount: 1

resources:
  requests:
    cpu: 2000m
    memory: 1024Mi

terminationGracePeriodSeconds: 1

service:
  type: NodePort
  nodePort: 30001
  port: 80

dev:
  hot_reload: true
  s3:
    url: "http://rustfs-svc.rustfs.svc.cluster.local:9000"
    bucket: bucket1

debug: true

s3:
  region: us-east-1
  access_key_id: rustfsadmin
  secret_access_key: rustfsadmin # pragma: allowlist secret

db:
  provider: rqlite
  baseUrl: http://rqlite.rqlite.svc.cluster.local
  username: dbuser
  password: dbuser # pragma: allowlist secret
  readinessProbe: /readyz

auth:
  basic:
    username: egressuser
    password: egressuser # pragma: allowlist secret
